name: Caller workflow

on:
  push:
    branches:
      - master

jobs:
  trigger-e2e-tests:
    name: Trigger e2e tests
    uses: './.github/workflows/e2e-tests.yml'
    with:
      initiator: Caller workflow
      message: Hello from a caller workflow
  check-results:
    name: Check e2e test results
    needs: trigger-e2e-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check results
        env:
          RESULT: ${{ needs.trigger-e2e-tests.outputs.outcome }}
        run: echo "The tests finished with the $RESULT status"