name: Matrix
run-name: ${{ inputs.initiator || 'Somebody' }}'s test run

on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - test-event
  workflow_dispatch:
    inputs:
      initiatior:
        type: string
        required: true
        description: Run initiator
      message:
        type: string
        required: false
        description: Some cool message for tests

jobs:
  e2e-tests:
    name: E2e tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        spec: [test.spec.ts, test2.spec.ts]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Check env
        env:
          ENV: ${{ toJSON(github) }}
        run: echo $ENV
      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test -- --spec test/specs/${{ matrix.spec }}
        env:
          SPEC_HASH: ${{ hashFiles(format('test/specs/{0}', matrix.spec)) }}
          VERY_SECRET_KEY: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.very_secret_key || '*****' }}
          MESSAGE: ${{ inputs.message || 'Missing message' }}
      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.spec }}-video
          path: test/videos
          retention-days: 1